---
AWSTemplateFormatVersion: 2010-09-09

Description: Amazon S3 bucket

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Parameters
        Parameters:
          - ParentStack
      - Label:
          default: Bucket Parameters
        Parameters:
          - BucketName
          - AccessControl
          - PolicyDocument
      - Label:
          default: Encryption Parameters
        Parameters:
          - EnableBucketEncryption
          - BucketKeyEnabled
          - SSEAlgorithm
          - KMSMasterKeyID
      - Label:
          default: Public Access Block
        Parameters:
          - BlockPublicAcls
          - BlockPublicPolicy
          - IgnorePublicAcls
          - RestrictPublicBuckets

Parameters:
  ParentStack:
    Type: String
    Description: (optional) If this stack is nested; name of the parent stack
    Default: ""

  BucketName:
    Type: String
    Description: >-
      (optional) A name for the bucket. If you don't specify a name, AWS
      CloudFormation generates a unique ID and uses that ID for the bucket name
    Default: ""

  AccessControl:
    Type: String
    Description: >-
      A canned access control list (ACL) that grants predefined permissions to
      the bucket
    Default: Private
    AllowedValues:
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthenticatedRead
      - LogDeliveryWrite
      - BucketOwnerRead
      - BucketOwnerFullControl
      - AwsExecRead

  PolicyDocument:
    Type: String
    Description: >-
      A policy document containing permissions to add to the specified bucket
    Default: ""

  ### Bucket Encryption ########################################################

  EnableBucketEncryption:
    Type: String
    Description: Enables bucket encryption
    Default: false
    AllowedValues:
      - true
      - false

  BucketKeyEnabled:
    Type: String
    Description: Enables bucket encryption
    Default: false
    AllowedValues:
      - true
      - false

  SSEAlgorithm:
    Type: String
    Description: >-
      Server-side encryption algorithm to use for the default encryption
    Default: aws:kms
    AllowedValues:
      - aws:kms
      - AES256

  KMSMasterKeyID:
    Type: String
    Description: >-
      (conditional: only applicable if SSEAlgorithm is aws:kms) KMS key ID to
      use for the default encryption. This parameter is allowed if SSEAlgorithm
      is aws:kms. You can specify the key ID or the Amazon Resource Name (ARN)
      of the CMK. However, if you are using encryption with cross-account
      operations, you must use a fully qualified CMK ARN. NOTE: Amazon S3 only
      supports symmetric KMS keys and not asymmetric KMS keys. e.g: Key ID:
      1234abcd-12ab-34cd-56ef-1234567890ab, Key ARN:
      arn:aws:kms:us-east-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab
    Default: ""

  ### Public Access Block ######################################################

  BlockPublicAcls:
    Type: String
    Description: >-
      Specifies whether Amazon S3 should block public access control lists
      (ACLs) for this bucket and objects in this bucket. Setting this element to
      TRUE causes the following behavior: (1) PUT Bucket acl and PUT Object acl
      calls fail if the specified ACL is public. (2) PUT Object calls fail if
      the request includes a public ACL. (3) PUT Bucket calls fail if the
      request includes a public ACL. NOTE: Enabling this setting doesn't affect
      existing policies or ACLs
    Default: true
    AllowedValues:
      - true
      - false

  BlockPublicPolicy:
    Type: String
    Description: >-
      Specifies whether Amazon S3 should block public bucket policies for this
      bucket. Setting this element to TRUE causes Amazon S3 to reject calls to
      PUT Bucket policy if the specified bucket policy allows public access.
      NOTE: Enabling this setting doesn't affect existing bucket policies
    Default: true
    AllowedValues:
      - true
      - false

  IgnorePublicAcls:
    Type: String
    Description: >-
      Specifies whether Amazon S3 should ignore public ACLs for this bucket and
      objects in this bucket. Setting this element to TRUE causes Amazon S3 to
      ignore all public ACLs on this bucket and objects in this bucket. NOTE:
        Enabling this setting doesn't affect the persistence of any existing
        ACLs and doesn't prevent new public ACLs from being set
    Default: true
    AllowedValues:
      - true
      - false

  RestrictPublicBuckets:
    Type: String
    Description: >-
      Specifies whether Amazon S3 should restrict public bucket policies for
      this bucket. Setting this element to TRUE restricts access to this bucket
      to only AWS service principals and authorized users within this account if
      the bucket has a public policy. NOTE: Enabling this setting doesn't affect
      previously stored bucket policies, except that public and cross-account
      access within any public bucket policy, including non-public delegation to
      specific accounts, is blocked
    Default: true
    AllowedValues:
      - true
      - false

Conditions:
  SpecifyParentStack: !Not [!Equals [!Ref ParentStack, ""]]
  SpecifyPolicy: !Not [!Equals [!Ref ParentStack, ""]]

Resources:

  bucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://$__BUCKET_NAME__.s3.eu-west-2.amazonaws.com/$__BUCKET_FOLDER__/s3/_bucket.yml"
      Parameters:
        ParentStack: !Ref "AWS::StackName"
        BucketName: !Ref BucketName
        AccessControl: !Ref AccessControl
        EnableBucketEncryption: !Ref EnableBucketEncryption
        BucketKeyEnabled: !Ref BucketKeyEnabled
        SSEAlgorithm: !Ref SSEAlgorithm
        KMSMasterKeyID: !Ref KMSMasterKeyID
        BlockPublicAcls: !Ref BlockPublicAcls
        BlockPublicPolicy: !Ref BlockPublicPolicy
        IgnorePublicAcls: !Ref IgnorePublicAcls
        RestrictPublicBuckets: !Ref RestrictPublicBuckets

  policyStack:
    Condition: SpecifyPolicy
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://$__BUCKET_NAME__.s3.eu-west-2.amazonaws.com/$__BUCKET_FOLDER__/s3/_policy.yml"
      Parameters:
        ParentStack: !Ref "AWS::StackName"
        Bucket: !Ref BucketName
        PolicyDocument: !Ref PolicyDocument

# Outputs:
  # specify when needed
